[package]
name = "iron-carrier"
version = "0.1.0"
authors = ["Ilson Roberto Balliego Junior"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bincode = "^1.3.3"
serde = { version = "1.0", features=["derive"] }
toml = "0.5.6"
filetime = "0.2"
tokio = { version= "1", features=["full"] }
futures= "0.3"
bytes = "0.5"
notify = "4.0.12"
log = "0.4.11"
stderrlog = "0.5.0"
clap = "2.33.3"
thiserror = "^1.0.0"
simple-mdns = "^0.1"
if-addrs = "0.6.5"

[dev-dependencies]
rand = "^0.8"
