version: "3.9"

services:
  ic_one:
    container_name: ic_one
    build:
      context: .
      dockerfile: Dockerfile.src
    # network_mode: "host"
    command: ["iron-carrier", "-vvvv", "/app/configs/config.one.toml"]
    networks:
      - ic-network
  ic_two:
    container_name: ic_two
    build: .
    # network_mode: "host"
    command: ["iron-carrier", "-vvvv", "/app/configs/config.two.toml"]
    networks:
      - ic-network

networks:
  ic-network:
    # internal: true
    # driver: "host"
