services:
  node1:
    image: localhost/iron-carrier
    build: ../../
    networks:
      - sync-net
    tmpfs:
      - /data
    volumes:
      - ../encrypted-config.toml:/config/config.toml:ro
      - ../../scripts/gen-files-from-list.sh:/scripts/gen-files-from-list.sh:ro
      - ./deleted-files.txt:/config/deleted-files.txt:ro
    entrypoint: sh -c '/scripts/gen-files-from-list.sh /data /config/deleted-files.txt && iron-carrier -vvd /config/config.toml'

  node2:
    image: localhost/iron-carrier
    build: ../../
    networks:
      - sync-net
    tmpfs:
      - /data
    volumes:
      - ../encrypted-config.toml:/config/config.toml:ro
      - ../../scripts/gen-files-from-list.sh:/scripts/gen-files-from-list.sh:ro
      - ./deleted-files.txt:/config/deleted-files.txt:ro
    entrypoint: sh -c '/scripts/gen-files-from-list.sh /data /config/deleted-files.txt && iron-carrier -vvd /config/config.toml'

  node3:
    image: localhost/iron-carrier
    build: ../../
    networks:
      - sync-net
    tmpfs:
      - /data
    volumes:
      - ../encrypted-config.toml:/config/config.toml:ro
      - ./seed-pre-deleted-db.sh:/scripts/seed-pre-deleted-db.sh:ro
      - ../../iron-carrier/src/transaction_log/database_setup.sql:/scripts/database_setup.sql:ro
      - ./deleted-files.txt:/config/deleted-files.txt:ro
    entrypoint: sh -c '/scripts/seed-pre-deleted-db.sh /app/iron-carrier.db /scripts/database_setup.sql /config/deleted-files.txt && sleep 1 && iron-carrier -vv /config/config.toml && echo "test completed" && sleep infinity'

networks:
  sync-net:
    driver: bridge
